### ISSUE TITLE
Whole Sign Houses system

### ISSUE THREAD

**Issue by OpakAlex** [Kibo/AstrologyChart2#1]
Hello,

Can i use your library to draw Whole Sign Houses system chart? 
Something like: 
<img width="671" alt="Screenshot 2023-08-08 at 18 40 25" src="https://github.com/Kibo/AstrologyChart2/assets/1227774/d055c85b-7114-45b1-bfce-1ea460161498">
Thanks!

**Comment by Kibo** [comment]
Hi Alex

Yes, you can.

**Comment by OpakAlex** [comment]
thanks for your answer!
Can you help me a little? how should look payload data for this one?
